In [1]:
import numpy as np

How to find maximum product of two integers in the array where all integers are positive 

In [5]:
def maximumProduct(array):
    product=0
    for i in range(len(array)):
        for j in range(i+1,len(array)):
            if array[i]*array[j]>=product:
                product=array[i]*array[j]
                pairs=str(array[i])+","+str(array[j])
    print(product)
    print(pairs)

In [6]:
myArray = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
print(maximumProduct(myArray))

380
19,20
None


In [7]:
#check whether elemnts are unique or not

In [13]:
def isunique(array):
    l=[]
    for i in array:
        if i in l:
            print(i)
            return False
        else:
            l.append(i)
    return True

In [14]:
aee=[1,2,3,4,5,6,5,8,9]
print(isunique(aee))

5
False


In [15]:
#Permutations qn
def permutation(list1,list2):
    if len(list1)!=len(list2):
        return False
    list1.sort()
    list2.sort()
    if list1==list2:
        return True
    else:
        return False
        
        

In [18]:
list1=["a","c","d"]
list2=["c","a","b"]
print(permutation(list1,list2))

False


In [19]:
#rotate matrix by 90

In [20]:
import numpy as np

In [23]:
myarray1=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
myarray1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
def rotateMatrix(matrix):
    n=len(matrix)#will give no of row 
    for layer in range(n//2):
        first=layer
        last=n-layer-1
        for i in range(first,last):
            #save top elemrnt
            top=matrix[layer][i]
            #move top element to left
            matrix[layer][i]=matrix[-i-1][layer]
            #move bottom element to left
            matrix[-i-1][layer]=matrix[-layer-1][-i-1]
            #move right to bottom
            matrix[-layer-1][-i-1]=matrix[i][-layer-1]
            #move to right
            matrix[i][-layer-1]=top
    return matrix

    
    

In [28]:
print(rotateMatrix(myarray1))

[[7 4 1]
 [8 5 2]
 [9 6 3]]
